steps:
  # Build the container image
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA
      - --cache=true
      - --cache-ttl=24h
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
      - '--region'
      - '$_REGION'
      - '--port'
      - '$_PORT'
images:
  - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
substitutions:
  _SERVICE_NAME: backend-loadmap # default value
  _REGION: asia-northeast1 # default value
  _PORT: "3000" # default value
